language: cpp
compiler: clang
before_script:
  - echo "\n" | sudo add-apt-repository ppa:zoogie/sdl2-snapshots
  - sudo apt-get update -qq
  - sudo apt-get install -qq libarchive-dev libboost1.48-dev libsdl2-dev libsdl2-mixer-dev libpixman-1-dev libdevil-dev
  - gem install libarchive iconv devil
  - git clone --depth 1 "https://github.com/EasyRPG/TestGame.git" "$RPG_TEST_GAME_PATH"
  - export RPG_TEST_GAME_PATH="$RPG_TEST_GAME_PATH/TestGame-2000"
  - git clone --branch dummy --depth 1 "https://github.com/take-cheeze/RTP.git" "$RPG_RTP_PATH"
script:
  - CXX="$CXX -std=c++11" ./build.sh all test
after_script:
  - cat ./mruby/easyrpg_log.txt
env:
  global:
    - RPG_RTP_PATH="$PWD/lib/RTP"
    - RPG_TEST_GAME_PATH="$PWD/lib/TestGame"
